name: cntk-py36
channels:
- defaults
# For imageio:
- conda-forge
dependencies:
- h5py
- imageio
- jupyter
- matplotlib
- numpy
- opencv
- pandas
- pandas-datareader
- pandoc
- pip
- python
- pyyaml
- scikit-image
- scikit-learn
- scipy
- seaborn
- setuptools
- six
- wheel
- pip:
  - easydict
  - gym[atari]
  - keras
  - pydot-ng
  - pygame
  - pytest
  - sphinx-rtd-theme
  - sphinx
  - nbsphinx
  - twine
  - protobuf
  - pillow